port: 5000
incoming_port: 6001
allowlist:
  - echo
  - ls
  - pwd
  - whoami
  - date
  - uptime
  - cd
  - mkdir
  - rmdir
  - touch
  - cat
  - cp
  - mv
  - rm
  - head
  - tail
  - grep
  - find
  - chmod
  - chown
  - tar
  - zip
  - unzip
  - ps
  - kill
  - sh
  - bash
  - python
  - pip
  - dir
  - type
  - copy
  - move
  - del
  - cls
  - start
  - tasklist
  - taskkill
  - powershell
  - sudo systemctl restart NetworkManager
lmstudio_servers:
  - url: "http://localhost:1234"
    token: ""
anythingllm_servers:
  - url: "http://localhost:3001"
    token: ""
n8n_servers:
  - url: "http://localhost:5678"
    token: ""
openai_servers:
  - url: "https://api.openai.com"
    token: ""
lmstudio_url: "http://localhost:1234"
lmstudio_token: ""
anythingllm_url: "http://localhost:3001"
anythingllm_token: ""
n8n_url: "http://localhost:5678"
n8n_token: ""
openai_url: "https://api.openai.com"
openai_token: ""
openai_model: "gpt-3.5-turbo"
