port: 5000
allowlist:
  - echo
  - ls
  - pwd
  - whoami
  - date
  - uptime
  - sudo systemctl restart NetworkManager
n8n_url: "http://localhost:5678"
n8n_token: ""
anythingllm_url: "http://localhost:3001"
anythingllm_token: ""
lmstudio_url: "http://localhost:1234"
lmstudio_token: ""
